# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artem/test_build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artem/test_build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/artem/test_build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/test_build/CMakeFiles /home/artem/test_build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/test_build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arch-post-installer

# Build rule for target.
arch-post-installer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arch-post-installer
.PHONY : arch-post-installer

# fast build rule for target.
arch-post-installer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/build
.PHONY : arch-post-installer/fast

#=============================================================================
# Target rules for targets named arch-post-installer_autogen

# Build rule for target.
arch-post-installer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arch-post-installer_autogen
.PHONY : arch-post-installer_autogen

# fast build rule for target.
arch-post-installer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer_autogen.dir/build.make CMakeFiles/arch-post-installer_autogen.dir/build
.PHONY : arch-post-installer_autogen/fast

app-centers/install-flatpak-software.o: app-centers/install-flatpak-software.cpp.o
.PHONY : app-centers/install-flatpak-software.o

# target to build an object file
app-centers/install-flatpak-software.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-flatpak-software.cpp.o
.PHONY : app-centers/install-flatpak-software.cpp.o

app-centers/install-flatpak-software.i: app-centers/install-flatpak-software.cpp.i
.PHONY : app-centers/install-flatpak-software.i

# target to preprocess a source file
app-centers/install-flatpak-software.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-flatpak-software.cpp.i
.PHONY : app-centers/install-flatpak-software.cpp.i

app-centers/install-flatpak-software.s: app-centers/install-flatpak-software.cpp.s
.PHONY : app-centers/install-flatpak-software.s

# target to generate assembly for a file
app-centers/install-flatpak-software.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-flatpak-software.cpp.s
.PHONY : app-centers/install-flatpak-software.cpp.s

app-centers/install-flatpak.o: app-centers/install-flatpak.cpp.o
.PHONY : app-centers/install-flatpak.o

# target to build an object file
app-centers/install-flatpak.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-flatpak.cpp.o
.PHONY : app-centers/install-flatpak.cpp.o

app-centers/install-flatpak.i: app-centers/install-flatpak.cpp.i
.PHONY : app-centers/install-flatpak.i

# target to preprocess a source file
app-centers/install-flatpak.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-flatpak.cpp.i
.PHONY : app-centers/install-flatpak.cpp.i

app-centers/install-flatpak.s: app-centers/install-flatpak.cpp.s
.PHONY : app-centers/install-flatpak.s

# target to generate assembly for a file
app-centers/install-flatpak.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-flatpak.cpp.s
.PHONY : app-centers/install-flatpak.cpp.s

app-centers/install-snapd.o: app-centers/install-snapd.cpp.o
.PHONY : app-centers/install-snapd.o

# target to build an object file
app-centers/install-snapd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-snapd.cpp.o
.PHONY : app-centers/install-snapd.cpp.o

app-centers/install-snapd.i: app-centers/install-snapd.cpp.i
.PHONY : app-centers/install-snapd.i

# target to preprocess a source file
app-centers/install-snapd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-snapd.cpp.i
.PHONY : app-centers/install-snapd.cpp.i

app-centers/install-snapd.s: app-centers/install-snapd.cpp.s
.PHONY : app-centers/install-snapd.s

# target to generate assembly for a file
app-centers/install-snapd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/app-centers/install-snapd.cpp.s
.PHONY : app-centers/install-snapd.cpp.s

arch-post-installer_autogen/mocs_compilation.o: arch-post-installer_autogen/mocs_compilation.cpp.o
.PHONY : arch-post-installer_autogen/mocs_compilation.o

# target to build an object file
arch-post-installer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/arch-post-installer_autogen/mocs_compilation.cpp.o
.PHONY : arch-post-installer_autogen/mocs_compilation.cpp.o

arch-post-installer_autogen/mocs_compilation.i: arch-post-installer_autogen/mocs_compilation.cpp.i
.PHONY : arch-post-installer_autogen/mocs_compilation.i

# target to preprocess a source file
arch-post-installer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/arch-post-installer_autogen/mocs_compilation.cpp.i
.PHONY : arch-post-installer_autogen/mocs_compilation.cpp.i

arch-post-installer_autogen/mocs_compilation.s: arch-post-installer_autogen/mocs_compilation.cpp.s
.PHONY : arch-post-installer_autogen/mocs_compilation.s

# target to generate assembly for a file
arch-post-installer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/arch-post-installer_autogen/mocs_compilation.cpp.s
.PHONY : arch-post-installer_autogen/mocs_compilation.cpp.s

cleaning/clear-font-cache.o: cleaning/clear-font-cache.cpp.o
.PHONY : cleaning/clear-font-cache.o

# target to build an object file
cleaning/clear-font-cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/cleaning/clear-font-cache.cpp.o
.PHONY : cleaning/clear-font-cache.cpp.o

cleaning/clear-font-cache.i: cleaning/clear-font-cache.cpp.i
.PHONY : cleaning/clear-font-cache.i

# target to preprocess a source file
cleaning/clear-font-cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/cleaning/clear-font-cache.cpp.i
.PHONY : cleaning/clear-font-cache.cpp.i

cleaning/clear-font-cache.s: cleaning/clear-font-cache.cpp.s
.PHONY : cleaning/clear-font-cache.s

# target to generate assembly for a file
cleaning/clear-font-cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/cleaning/clear-font-cache.cpp.s
.PHONY : cleaning/clear-font-cache.cpp.s

cleaning/install-system-clean.o: cleaning/install-system-clean.cpp.o
.PHONY : cleaning/install-system-clean.o

# target to build an object file
cleaning/install-system-clean.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/cleaning/install-system-clean.cpp.o
.PHONY : cleaning/install-system-clean.cpp.o

cleaning/install-system-clean.i: cleaning/install-system-clean.cpp.i
.PHONY : cleaning/install-system-clean.i

# target to preprocess a source file
cleaning/install-system-clean.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/cleaning/install-system-clean.cpp.i
.PHONY : cleaning/install-system-clean.cpp.i

cleaning/install-system-clean.s: cleaning/install-system-clean.cpp.s
.PHONY : cleaning/install-system-clean.s

# target to generate assembly for a file
cleaning/install-system-clean.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/cleaning/install-system-clean.cpp.s
.PHONY : cleaning/install-system-clean.cpp.s

create-sh-file.o: create-sh-file.cpp.o
.PHONY : create-sh-file.o

# target to build an object file
create-sh-file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/create-sh-file.cpp.o
.PHONY : create-sh-file.cpp.o

create-sh-file.i: create-sh-file.cpp.i
.PHONY : create-sh-file.i

# target to preprocess a source file
create-sh-file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/create-sh-file.cpp.i
.PHONY : create-sh-file.cpp.i

create-sh-file.s: create-sh-file.cpp.s
.PHONY : create-sh-file.s

# target to generate assembly for a file
create-sh-file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/create-sh-file.cpp.s
.PHONY : create-sh-file.cpp.s

de/install-de-cinnamon.o: de/install-de-cinnamon.cpp.o
.PHONY : de/install-de-cinnamon.o

# target to build an object file
de/install-de-cinnamon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-cinnamon.cpp.o
.PHONY : de/install-de-cinnamon.cpp.o

de/install-de-cinnamon.i: de/install-de-cinnamon.cpp.i
.PHONY : de/install-de-cinnamon.i

# target to preprocess a source file
de/install-de-cinnamon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-cinnamon.cpp.i
.PHONY : de/install-de-cinnamon.cpp.i

de/install-de-cinnamon.s: de/install-de-cinnamon.cpp.s
.PHONY : de/install-de-cinnamon.s

# target to generate assembly for a file
de/install-de-cinnamon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-cinnamon.cpp.s
.PHONY : de/install-de-cinnamon.cpp.s

de/install-de-deepin.o: de/install-de-deepin.cpp.o
.PHONY : de/install-de-deepin.o

# target to build an object file
de/install-de-deepin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-deepin.cpp.o
.PHONY : de/install-de-deepin.cpp.o

de/install-de-deepin.i: de/install-de-deepin.cpp.i
.PHONY : de/install-de-deepin.i

# target to preprocess a source file
de/install-de-deepin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-deepin.cpp.i
.PHONY : de/install-de-deepin.cpp.i

de/install-de-deepin.s: de/install-de-deepin.cpp.s
.PHONY : de/install-de-deepin.s

# target to generate assembly for a file
de/install-de-deepin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-deepin.cpp.s
.PHONY : de/install-de-deepin.cpp.s

de/install-de-enl.o: de/install-de-enl.cpp.o
.PHONY : de/install-de-enl.o

# target to build an object file
de/install-de-enl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-enl.cpp.o
.PHONY : de/install-de-enl.cpp.o

de/install-de-enl.i: de/install-de-enl.cpp.i
.PHONY : de/install-de-enl.i

# target to preprocess a source file
de/install-de-enl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-enl.cpp.i
.PHONY : de/install-de-enl.cpp.i

de/install-de-enl.s: de/install-de-enl.cpp.s
.PHONY : de/install-de-enl.s

# target to generate assembly for a file
de/install-de-enl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-enl.cpp.s
.PHONY : de/install-de-enl.cpp.s

de/install-de-lxde.o: de/install-de-lxde.cpp.o
.PHONY : de/install-de-lxde.o

# target to build an object file
de/install-de-lxde.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-lxde.cpp.o
.PHONY : de/install-de-lxde.cpp.o

de/install-de-lxde.i: de/install-de-lxde.cpp.i
.PHONY : de/install-de-lxde.i

# target to preprocess a source file
de/install-de-lxde.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-lxde.cpp.i
.PHONY : de/install-de-lxde.cpp.i

de/install-de-lxde.s: de/install-de-lxde.cpp.s
.PHONY : de/install-de-lxde.s

# target to generate assembly for a file
de/install-de-lxde.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-lxde.cpp.s
.PHONY : de/install-de-lxde.cpp.s

de/install-de-lxqt.o: de/install-de-lxqt.cpp.o
.PHONY : de/install-de-lxqt.o

# target to build an object file
de/install-de-lxqt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-lxqt.cpp.o
.PHONY : de/install-de-lxqt.cpp.o

de/install-de-lxqt.i: de/install-de-lxqt.cpp.i
.PHONY : de/install-de-lxqt.i

# target to preprocess a source file
de/install-de-lxqt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-lxqt.cpp.i
.PHONY : de/install-de-lxqt.cpp.i

de/install-de-lxqt.s: de/install-de-lxqt.cpp.s
.PHONY : de/install-de-lxqt.s

# target to generate assembly for a file
de/install-de-lxqt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-lxqt.cpp.s
.PHONY : de/install-de-lxqt.cpp.s

de/install-de-mate.o: de/install-de-mate.cpp.o
.PHONY : de/install-de-mate.o

# target to build an object file
de/install-de-mate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-mate.cpp.o
.PHONY : de/install-de-mate.cpp.o

de/install-de-mate.i: de/install-de-mate.cpp.i
.PHONY : de/install-de-mate.i

# target to preprocess a source file
de/install-de-mate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-mate.cpp.i
.PHONY : de/install-de-mate.cpp.i

de/install-de-mate.s: de/install-de-mate.cpp.s
.PHONY : de/install-de-mate.s

# target to generate assembly for a file
de/install-de-mate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-mate.cpp.s
.PHONY : de/install-de-mate.cpp.s

de/install-de-plasma.o: de/install-de-plasma.cpp.o
.PHONY : de/install-de-plasma.o

# target to build an object file
de/install-de-plasma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-plasma.cpp.o
.PHONY : de/install-de-plasma.cpp.o

de/install-de-plasma.i: de/install-de-plasma.cpp.i
.PHONY : de/install-de-plasma.i

# target to preprocess a source file
de/install-de-plasma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-plasma.cpp.i
.PHONY : de/install-de-plasma.cpp.i

de/install-de-plasma.s: de/install-de-plasma.cpp.s
.PHONY : de/install-de-plasma.s

# target to generate assembly for a file
de/install-de-plasma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-plasma.cpp.s
.PHONY : de/install-de-plasma.cpp.s

de/install-de-xfce4.o: de/install-de-xfce4.cpp.o
.PHONY : de/install-de-xfce4.o

# target to build an object file
de/install-de-xfce4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-xfce4.cpp.o
.PHONY : de/install-de-xfce4.cpp.o

de/install-de-xfce4.i: de/install-de-xfce4.cpp.i
.PHONY : de/install-de-xfce4.i

# target to preprocess a source file
de/install-de-xfce4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-xfce4.cpp.i
.PHONY : de/install-de-xfce4.cpp.i

de/install-de-xfce4.s: de/install-de-xfce4.cpp.s
.PHONY : de/install-de-xfce4.s

# target to generate assembly for a file
de/install-de-xfce4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-de-xfce4.cpp.s
.PHONY : de/install-de-xfce4.cpp.s

de/install-gnome.o: de/install-gnome.cpp.o
.PHONY : de/install-gnome.o

# target to build an object file
de/install-gnome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-gnome.cpp.o
.PHONY : de/install-gnome.cpp.o

de/install-gnome.i: de/install-gnome.cpp.i
.PHONY : de/install-gnome.i

# target to preprocess a source file
de/install-gnome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-gnome.cpp.i
.PHONY : de/install-gnome.cpp.i

de/install-gnome.s: de/install-gnome.cpp.s
.PHONY : de/install-gnome.s

# target to generate assembly for a file
de/install-gnome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/de/install-gnome.cpp.s
.PHONY : de/install-gnome.cpp.s

general/install-auto-freq.o: general/install-auto-freq.cpp.o
.PHONY : general/install-auto-freq.o

# target to build an object file
general/install-auto-freq.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-auto-freq.cpp.o
.PHONY : general/install-auto-freq.cpp.o

general/install-auto-freq.i: general/install-auto-freq.cpp.i
.PHONY : general/install-auto-freq.i

# target to preprocess a source file
general/install-auto-freq.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-auto-freq.cpp.i
.PHONY : general/install-auto-freq.cpp.i

general/install-auto-freq.s: general/install-auto-freq.cpp.s
.PHONY : general/install-auto-freq.s

# target to generate assembly for a file
general/install-auto-freq.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-auto-freq.cpp.s
.PHONY : general/install-auto-freq.cpp.s

general/install-freq.o: general/install-freq.cpp.o
.PHONY : general/install-freq.o

# target to build an object file
general/install-freq.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-freq.cpp.o
.PHONY : general/install-freq.cpp.o

general/install-freq.i: general/install-freq.cpp.i
.PHONY : general/install-freq.i

# target to preprocess a source file
general/install-freq.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-freq.cpp.i
.PHONY : general/install-freq.cpp.i

general/install-freq.s: general/install-freq.cpp.s
.PHONY : general/install-freq.s

# target to generate assembly for a file
general/install-freq.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-freq.cpp.s
.PHONY : general/install-freq.cpp.s

general/install-keys.o: general/install-keys.cpp.o
.PHONY : general/install-keys.o

# target to build an object file
general/install-keys.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-keys.cpp.o
.PHONY : general/install-keys.cpp.o

general/install-keys.i: general/install-keys.cpp.i
.PHONY : general/install-keys.i

# target to preprocess a source file
general/install-keys.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-keys.cpp.i
.PHONY : general/install-keys.cpp.i

general/install-keys.s: general/install-keys.cpp.s
.PHONY : general/install-keys.s

# target to generate assembly for a file
general/install-keys.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-keys.cpp.s
.PHONY : general/install-keys.cpp.s

general/install-make-tools.o: general/install-make-tools.cpp.o
.PHONY : general/install-make-tools.o

# target to build an object file
general/install-make-tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-make-tools.cpp.o
.PHONY : general/install-make-tools.cpp.o

general/install-make-tools.i: general/install-make-tools.cpp.i
.PHONY : general/install-make-tools.i

# target to preprocess a source file
general/install-make-tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-make-tools.cpp.i
.PHONY : general/install-make-tools.cpp.i

general/install-make-tools.s: general/install-make-tools.cpp.s
.PHONY : general/install-make-tools.s

# target to generate assembly for a file
general/install-make-tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-make-tools.cpp.s
.PHONY : general/install-make-tools.cpp.s

general/install-mirrors.o: general/install-mirrors.cpp.o
.PHONY : general/install-mirrors.o

# target to build an object file
general/install-mirrors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-mirrors.cpp.o
.PHONY : general/install-mirrors.cpp.o

general/install-mirrors.i: general/install-mirrors.cpp.i
.PHONY : general/install-mirrors.i

# target to preprocess a source file
general/install-mirrors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-mirrors.cpp.i
.PHONY : general/install-mirrors.cpp.i

general/install-mirrors.s: general/install-mirrors.cpp.s
.PHONY : general/install-mirrors.s

# target to generate assembly for a file
general/install-mirrors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-mirrors.cpp.s
.PHONY : general/install-mirrors.cpp.s

general/install-system-tools.o: general/install-system-tools.cpp.o
.PHONY : general/install-system-tools.o

# target to build an object file
general/install-system-tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-system-tools.cpp.o
.PHONY : general/install-system-tools.cpp.o

general/install-system-tools.i: general/install-system-tools.cpp.i
.PHONY : general/install-system-tools.i

# target to preprocess a source file
general/install-system-tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-system-tools.cpp.i
.PHONY : general/install-system-tools.cpp.i

general/install-system-tools.s: general/install-system-tools.cpp.s
.PHONY : general/install-system-tools.s

# target to generate assembly for a file
general/install-system-tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/general/install-system-tools.cpp.s
.PHONY : general/install-system-tools.cpp.s

greeter/install-greeter.o: greeter/install-greeter.cpp.o
.PHONY : greeter/install-greeter.o

# target to build an object file
greeter/install-greeter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/greeter/install-greeter.cpp.o
.PHONY : greeter/install-greeter.cpp.o

greeter/install-greeter.i: greeter/install-greeter.cpp.i
.PHONY : greeter/install-greeter.i

# target to preprocess a source file
greeter/install-greeter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/greeter/install-greeter.cpp.i
.PHONY : greeter/install-greeter.cpp.i

greeter/install-greeter.s: greeter/install-greeter.cpp.s
.PHONY : greeter/install-greeter.s

# target to generate assembly for a file
greeter/install-greeter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/greeter/install-greeter.cpp.s
.PHONY : greeter/install-greeter.cpp.s

install-networking.o: install-networking.cpp.o
.PHONY : install-networking.o

# target to build an object file
install-networking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/install-networking.cpp.o
.PHONY : install-networking.cpp.o

install-networking.i: install-networking.cpp.i
.PHONY : install-networking.i

# target to preprocess a source file
install-networking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/install-networking.cpp.i
.PHONY : install-networking.cpp.i

install-networking.s: install-networking.cpp.s
.PHONY : install-networking.s

# target to generate assembly for a file
install-networking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/install-networking.cpp.s
.PHONY : install-networking.cpp.s

install-proc.o: install-proc.cpp.o
.PHONY : install-proc.o

# target to build an object file
install-proc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/install-proc.cpp.o
.PHONY : install-proc.cpp.o

install-proc.i: install-proc.cpp.i
.PHONY : install-proc.i

# target to preprocess a source file
install-proc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/install-proc.cpp.i
.PHONY : install-proc.cpp.i

install-proc.s: install-proc.cpp.s
.PHONY : install-proc.s

# target to generate assembly for a file
install-proc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/install-proc.cpp.s
.PHONY : install-proc.cpp.s

kernels/install-lqx.o: kernels/install-lqx.cpp.o
.PHONY : kernels/install-lqx.o

# target to build an object file
kernels/install-lqx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-lqx.cpp.o
.PHONY : kernels/install-lqx.cpp.o

kernels/install-lqx.i: kernels/install-lqx.cpp.i
.PHONY : kernels/install-lqx.i

# target to preprocess a source file
kernels/install-lqx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-lqx.cpp.i
.PHONY : kernels/install-lqx.cpp.i

kernels/install-lqx.s: kernels/install-lqx.cpp.s
.PHONY : kernels/install-lqx.s

# target to generate assembly for a file
kernels/install-lqx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-lqx.cpp.s
.PHONY : kernels/install-lqx.cpp.s

kernels/install-pf-kernel.o: kernels/install-pf-kernel.cpp.o
.PHONY : kernels/install-pf-kernel.o

# target to build an object file
kernels/install-pf-kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-pf-kernel.cpp.o
.PHONY : kernels/install-pf-kernel.cpp.o

kernels/install-pf-kernel.i: kernels/install-pf-kernel.cpp.i
.PHONY : kernels/install-pf-kernel.i

# target to preprocess a source file
kernels/install-pf-kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-pf-kernel.cpp.i
.PHONY : kernels/install-pf-kernel.cpp.i

kernels/install-pf-kernel.s: kernels/install-pf-kernel.cpp.s
.PHONY : kernels/install-pf-kernel.s

# target to generate assembly for a file
kernels/install-pf-kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-pf-kernel.cpp.s
.PHONY : kernels/install-pf-kernel.cpp.s

kernels/install-tkg-kernel.o: kernels/install-tkg-kernel.cpp.o
.PHONY : kernels/install-tkg-kernel.o

# target to build an object file
kernels/install-tkg-kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-tkg-kernel.cpp.o
.PHONY : kernels/install-tkg-kernel.cpp.o

kernels/install-tkg-kernel.i: kernels/install-tkg-kernel.cpp.i
.PHONY : kernels/install-tkg-kernel.i

# target to preprocess a source file
kernels/install-tkg-kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-tkg-kernel.cpp.i
.PHONY : kernels/install-tkg-kernel.cpp.i

kernels/install-tkg-kernel.s: kernels/install-tkg-kernel.cpp.s
.PHONY : kernels/install-tkg-kernel.s

# target to generate assembly for a file
kernels/install-tkg-kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-tkg-kernel.cpp.s
.PHONY : kernels/install-tkg-kernel.cpp.s

kernels/install-xanmod.o: kernels/install-xanmod.cpp.o
.PHONY : kernels/install-xanmod.o

# target to build an object file
kernels/install-xanmod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-xanmod.cpp.o
.PHONY : kernels/install-xanmod.cpp.o

kernels/install-xanmod.i: kernels/install-xanmod.cpp.i
.PHONY : kernels/install-xanmod.i

# target to preprocess a source file
kernels/install-xanmod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-xanmod.cpp.i
.PHONY : kernels/install-xanmod.cpp.i

kernels/install-xanmod.s: kernels/install-xanmod.cpp.s
.PHONY : kernels/install-xanmod.s

# target to generate assembly for a file
kernels/install-xanmod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/kernels/install-xanmod.cpp.s
.PHONY : kernels/install-xanmod.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

misc/install-dev-tools.o: misc/install-dev-tools.cpp.o
.PHONY : misc/install-dev-tools.o

# target to build an object file
misc/install-dev-tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/misc/install-dev-tools.cpp.o
.PHONY : misc/install-dev-tools.cpp.o

misc/install-dev-tools.i: misc/install-dev-tools.cpp.i
.PHONY : misc/install-dev-tools.i

# target to preprocess a source file
misc/install-dev-tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/misc/install-dev-tools.cpp.i
.PHONY : misc/install-dev-tools.cpp.i

misc/install-dev-tools.s: misc/install-dev-tools.cpp.s
.PHONY : misc/install-dev-tools.s

# target to generate assembly for a file
misc/install-dev-tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/misc/install-dev-tools.cpp.s
.PHONY : misc/install-dev-tools.cpp.s

misc/install-wine.o: misc/install-wine.cpp.o
.PHONY : misc/install-wine.o

# target to build an object file
misc/install-wine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/misc/install-wine.cpp.o
.PHONY : misc/install-wine.cpp.o

misc/install-wine.i: misc/install-wine.cpp.i
.PHONY : misc/install-wine.i

# target to preprocess a source file
misc/install-wine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/misc/install-wine.cpp.i
.PHONY : misc/install-wine.cpp.i

misc/install-wine.s: misc/install-wine.cpp.s
.PHONY : misc/install-wine.s

# target to generate assembly for a file
misc/install-wine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/misc/install-wine.cpp.s
.PHONY : misc/install-wine.cpp.s

one-row-scripts.o: one-row-scripts.cpp.o
.PHONY : one-row-scripts.o

# target to build an object file
one-row-scripts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/one-row-scripts.cpp.o
.PHONY : one-row-scripts.cpp.o

one-row-scripts.i: one-row-scripts.cpp.i
.PHONY : one-row-scripts.i

# target to preprocess a source file
one-row-scripts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/one-row-scripts.cpp.i
.PHONY : one-row-scripts.cpp.i

one-row-scripts.s: one-row-scripts.cpp.s
.PHONY : one-row-scripts.s

# target to generate assembly for a file
one-row-scripts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/one-row-scripts.cpp.s
.PHONY : one-row-scripts.cpp.s

optimization/enable-trim.o: optimization/enable-trim.cpp.o
.PHONY : optimization/enable-trim.o

# target to build an object file
optimization/enable-trim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/enable-trim.cpp.o
.PHONY : optimization/enable-trim.cpp.o

optimization/enable-trim.i: optimization/enable-trim.cpp.i
.PHONY : optimization/enable-trim.i

# target to preprocess a source file
optimization/enable-trim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/enable-trim.cpp.i
.PHONY : optimization/enable-trim.cpp.i

optimization/enable-trim.s: optimization/enable-trim.cpp.s
.PHONY : optimization/enable-trim.s

# target to generate assembly for a file
optimization/enable-trim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/enable-trim.cpp.s
.PHONY : optimization/enable-trim.cpp.s

optimization/install-ananicy.o: optimization/install-ananicy.cpp.o
.PHONY : optimization/install-ananicy.o

# target to build an object file
optimization/install-ananicy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-ananicy.cpp.o
.PHONY : optimization/install-ananicy.cpp.o

optimization/install-ananicy.i: optimization/install-ananicy.cpp.i
.PHONY : optimization/install-ananicy.i

# target to preprocess a source file
optimization/install-ananicy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-ananicy.cpp.i
.PHONY : optimization/install-ananicy.cpp.i

optimization/install-ananicy.s: optimization/install-ananicy.cpp.s
.PHONY : optimization/install-ananicy.s

# target to generate assembly for a file
optimization/install-ananicy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-ananicy.cpp.s
.PHONY : optimization/install-ananicy.cpp.s

optimization/install-haveged.o: optimization/install-haveged.cpp.o
.PHONY : optimization/install-haveged.o

# target to build an object file
optimization/install-haveged.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-haveged.cpp.o
.PHONY : optimization/install-haveged.cpp.o

optimization/install-haveged.i: optimization/install-haveged.cpp.i
.PHONY : optimization/install-haveged.i

# target to preprocess a source file
optimization/install-haveged.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-haveged.cpp.i
.PHONY : optimization/install-haveged.cpp.i

optimization/install-haveged.s: optimization/install-haveged.cpp.s
.PHONY : optimization/install-haveged.s

# target to generate assembly for a file
optimization/install-haveged.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-haveged.cpp.s
.PHONY : optimization/install-haveged.cpp.s

optimization/install-nohang.o: optimization/install-nohang.cpp.o
.PHONY : optimization/install-nohang.o

# target to build an object file
optimization/install-nohang.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-nohang.cpp.o
.PHONY : optimization/install-nohang.cpp.o

optimization/install-nohang.i: optimization/install-nohang.cpp.i
.PHONY : optimization/install-nohang.i

# target to preprocess a source file
optimization/install-nohang.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-nohang.cpp.i
.PHONY : optimization/install-nohang.cpp.i

optimization/install-nohang.s: optimization/install-nohang.cpp.s
.PHONY : optimization/install-nohang.s

# target to generate assembly for a file
optimization/install-nohang.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-nohang.cpp.s
.PHONY : optimization/install-nohang.cpp.s

optimization/install-rng.o: optimization/install-rng.cpp.o
.PHONY : optimization/install-rng.o

# target to build an object file
optimization/install-rng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-rng.cpp.o
.PHONY : optimization/install-rng.cpp.o

optimization/install-rng.i: optimization/install-rng.cpp.i
.PHONY : optimization/install-rng.i

# target to preprocess a source file
optimization/install-rng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-rng.cpp.i
.PHONY : optimization/install-rng.cpp.i

optimization/install-rng.s: optimization/install-rng.cpp.s
.PHONY : optimization/install-rng.s

# target to generate assembly for a file
optimization/install-rng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-rng.cpp.s
.PHONY : optimization/install-rng.cpp.s

optimization/install-zramswap.o: optimization/install-zramswap.cpp.o
.PHONY : optimization/install-zramswap.o

# target to build an object file
optimization/install-zramswap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-zramswap.cpp.o
.PHONY : optimization/install-zramswap.cpp.o

optimization/install-zramswap.i: optimization/install-zramswap.cpp.i
.PHONY : optimization/install-zramswap.i

# target to preprocess a source file
optimization/install-zramswap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-zramswap.cpp.i
.PHONY : optimization/install-zramswap.cpp.i

optimization/install-zramswap.s: optimization/install-zramswap.cpp.s
.PHONY : optimization/install-zramswap.s

# target to generate assembly for a file
optimization/install-zramswap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/optimization/install-zramswap.cpp.s
.PHONY : optimization/install-zramswap.cpp.s

privacy/install-internet-tools.o: privacy/install-internet-tools.cpp.o
.PHONY : privacy/install-internet-tools.o

# target to build an object file
privacy/install-internet-tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-internet-tools.cpp.o
.PHONY : privacy/install-internet-tools.cpp.o

privacy/install-internet-tools.i: privacy/install-internet-tools.cpp.i
.PHONY : privacy/install-internet-tools.i

# target to preprocess a source file
privacy/install-internet-tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-internet-tools.cpp.i
.PHONY : privacy/install-internet-tools.cpp.i

privacy/install-internet-tools.s: privacy/install-internet-tools.cpp.s
.PHONY : privacy/install-internet-tools.s

# target to generate assembly for a file
privacy/install-internet-tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-internet-tools.cpp.s
.PHONY : privacy/install-internet-tools.cpp.s

privacy/install-messengers.o: privacy/install-messengers.cpp.o
.PHONY : privacy/install-messengers.o

# target to build an object file
privacy/install-messengers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-messengers.cpp.o
.PHONY : privacy/install-messengers.cpp.o

privacy/install-messengers.i: privacy/install-messengers.cpp.i
.PHONY : privacy/install-messengers.i

# target to preprocess a source file
privacy/install-messengers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-messengers.cpp.i
.PHONY : privacy/install-messengers.cpp.i

privacy/install-messengers.s: privacy/install-messengers.cpp.s
.PHONY : privacy/install-messengers.s

# target to generate assembly for a file
privacy/install-messengers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-messengers.cpp.s
.PHONY : privacy/install-messengers.cpp.s

privacy/install-security-tools.o: privacy/install-security-tools.cpp.o
.PHONY : privacy/install-security-tools.o

# target to build an object file
privacy/install-security-tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-security-tools.cpp.o
.PHONY : privacy/install-security-tools.cpp.o

privacy/install-security-tools.i: privacy/install-security-tools.cpp.i
.PHONY : privacy/install-security-tools.i

# target to preprocess a source file
privacy/install-security-tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-security-tools.cpp.i
.PHONY : privacy/install-security-tools.cpp.i

privacy/install-security-tools.s: privacy/install-security-tools.cpp.s
.PHONY : privacy/install-security-tools.s

# target to generate assembly for a file
privacy/install-security-tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/privacy/install-security-tools.cpp.s
.PHONY : privacy/install-security-tools.cpp.s

sound/install-alsa-sound.o: sound/install-alsa-sound.cpp.o
.PHONY : sound/install-alsa-sound.o

# target to build an object file
sound/install-alsa-sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-alsa-sound.cpp.o
.PHONY : sound/install-alsa-sound.cpp.o

sound/install-alsa-sound.i: sound/install-alsa-sound.cpp.i
.PHONY : sound/install-alsa-sound.i

# target to preprocess a source file
sound/install-alsa-sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-alsa-sound.cpp.i
.PHONY : sound/install-alsa-sound.cpp.i

sound/install-alsa-sound.s: sound/install-alsa-sound.cpp.s
.PHONY : sound/install-alsa-sound.s

# target to generate assembly for a file
sound/install-alsa-sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-alsa-sound.cpp.s
.PHONY : sound/install-alsa-sound.cpp.s

sound/install-audio-players.o: sound/install-audio-players.cpp.o
.PHONY : sound/install-audio-players.o

# target to build an object file
sound/install-audio-players.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-audio-players.cpp.o
.PHONY : sound/install-audio-players.cpp.o

sound/install-audio-players.i: sound/install-audio-players.cpp.i
.PHONY : sound/install-audio-players.i

# target to preprocess a source file
sound/install-audio-players.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-audio-players.cpp.i
.PHONY : sound/install-audio-players.cpp.i

sound/install-audio-players.s: sound/install-audio-players.cpp.s
.PHONY : sound/install-audio-players.s

# target to generate assembly for a file
sound/install-audio-players.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-audio-players.cpp.s
.PHONY : sound/install-audio-players.cpp.s

sound/install-bluetooth-actions.o: sound/install-bluetooth-actions.cpp.o
.PHONY : sound/install-bluetooth-actions.o

# target to build an object file
sound/install-bluetooth-actions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-bluetooth-actions.cpp.o
.PHONY : sound/install-bluetooth-actions.cpp.o

sound/install-bluetooth-actions.i: sound/install-bluetooth-actions.cpp.i
.PHONY : sound/install-bluetooth-actions.i

# target to preprocess a source file
sound/install-bluetooth-actions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-bluetooth-actions.cpp.i
.PHONY : sound/install-bluetooth-actions.cpp.i

sound/install-bluetooth-actions.s: sound/install-bluetooth-actions.cpp.s
.PHONY : sound/install-bluetooth-actions.s

# target to generate assembly for a file
sound/install-bluetooth-actions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-bluetooth-actions.cpp.s
.PHONY : sound/install-bluetooth-actions.cpp.s

sound/install-pipewire-sound.o: sound/install-pipewire-sound.cpp.o
.PHONY : sound/install-pipewire-sound.o

# target to build an object file
sound/install-pipewire-sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-pipewire-sound.cpp.o
.PHONY : sound/install-pipewire-sound.cpp.o

sound/install-pipewire-sound.i: sound/install-pipewire-sound.cpp.i
.PHONY : sound/install-pipewire-sound.i

# target to preprocess a source file
sound/install-pipewire-sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-pipewire-sound.cpp.i
.PHONY : sound/install-pipewire-sound.cpp.i

sound/install-pipewire-sound.s: sound/install-pipewire-sound.cpp.s
.PHONY : sound/install-pipewire-sound.s

# target to generate assembly for a file
sound/install-pipewire-sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-pipewire-sound.cpp.s
.PHONY : sound/install-pipewire-sound.cpp.s

sound/install-pulse-audio.o: sound/install-pulse-audio.cpp.o
.PHONY : sound/install-pulse-audio.o

# target to build an object file
sound/install-pulse-audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-pulse-audio.cpp.o
.PHONY : sound/install-pulse-audio.cpp.o

sound/install-pulse-audio.i: sound/install-pulse-audio.cpp.i
.PHONY : sound/install-pulse-audio.i

# target to preprocess a source file
sound/install-pulse-audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-pulse-audio.cpp.i
.PHONY : sound/install-pulse-audio.cpp.i

sound/install-pulse-audio.s: sound/install-pulse-audio.cpp.s
.PHONY : sound/install-pulse-audio.s

# target to generate assembly for a file
sound/install-pulse-audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/sound/install-pulse-audio.cpp.s
.PHONY : sound/install-pulse-audio.cpp.s

tweaks/gnome-tweaks.o: tweaks/gnome-tweaks.cpp.o
.PHONY : tweaks/gnome-tweaks.o

# target to build an object file
tweaks/gnome-tweaks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/gnome-tweaks.cpp.o
.PHONY : tweaks/gnome-tweaks.cpp.o

tweaks/gnome-tweaks.i: tweaks/gnome-tweaks.cpp.i
.PHONY : tweaks/gnome-tweaks.i

# target to preprocess a source file
tweaks/gnome-tweaks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/gnome-tweaks.cpp.i
.PHONY : tweaks/gnome-tweaks.cpp.i

tweaks/gnome-tweaks.s: tweaks/gnome-tweaks.cpp.s
.PHONY : tweaks/gnome-tweaks.s

# target to generate assembly for a file
tweaks/gnome-tweaks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/gnome-tweaks.cpp.s
.PHONY : tweaks/gnome-tweaks.cpp.s

tweaks/optimize-cinnamon.o: tweaks/optimize-cinnamon.cpp.o
.PHONY : tweaks/optimize-cinnamon.o

# target to build an object file
tweaks/optimize-cinnamon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/optimize-cinnamon.cpp.o
.PHONY : tweaks/optimize-cinnamon.cpp.o

tweaks/optimize-cinnamon.i: tweaks/optimize-cinnamon.cpp.i
.PHONY : tweaks/optimize-cinnamon.i

# target to preprocess a source file
tweaks/optimize-cinnamon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/optimize-cinnamon.cpp.i
.PHONY : tweaks/optimize-cinnamon.cpp.i

tweaks/optimize-cinnamon.s: tweaks/optimize-cinnamon.cpp.s
.PHONY : tweaks/optimize-cinnamon.s

# target to generate assembly for a file
tweaks/optimize-cinnamon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/optimize-cinnamon.cpp.s
.PHONY : tweaks/optimize-cinnamon.cpp.s

tweaks/plasma-tweaks.o: tweaks/plasma-tweaks.cpp.o
.PHONY : tweaks/plasma-tweaks.o

# target to build an object file
tweaks/plasma-tweaks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/plasma-tweaks.cpp.o
.PHONY : tweaks/plasma-tweaks.cpp.o

tweaks/plasma-tweaks.i: tweaks/plasma-tweaks.cpp.i
.PHONY : tweaks/plasma-tweaks.i

# target to preprocess a source file
tweaks/plasma-tweaks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/plasma-tweaks.cpp.i
.PHONY : tweaks/plasma-tweaks.cpp.i

tweaks/plasma-tweaks.s: tweaks/plasma-tweaks.cpp.s
.PHONY : tweaks/plasma-tweaks.s

# target to generate assembly for a file
tweaks/plasma-tweaks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/plasma-tweaks.cpp.s
.PHONY : tweaks/plasma-tweaks.cpp.s

tweaks/xfce4-tweaks.o: tweaks/xfce4-tweaks.cpp.o
.PHONY : tweaks/xfce4-tweaks.o

# target to build an object file
tweaks/xfce4-tweaks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/xfce4-tweaks.cpp.o
.PHONY : tweaks/xfce4-tweaks.cpp.o

tweaks/xfce4-tweaks.i: tweaks/xfce4-tweaks.cpp.i
.PHONY : tweaks/xfce4-tweaks.i

# target to preprocess a source file
tweaks/xfce4-tweaks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/xfce4-tweaks.cpp.i
.PHONY : tweaks/xfce4-tweaks.cpp.i

tweaks/xfce4-tweaks.s: tweaks/xfce4-tweaks.cpp.s
.PHONY : tweaks/xfce4-tweaks.s

# target to generate assembly for a file
tweaks/xfce4-tweaks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/tweaks/xfce4-tweaks.cpp.s
.PHONY : tweaks/xfce4-tweaks.cpp.s

video/install-dbus.o: video/install-dbus.cpp.o
.PHONY : video/install-dbus.o

# target to build an object file
video/install-dbus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-dbus.cpp.o
.PHONY : video/install-dbus.cpp.o

video/install-dbus.i: video/install-dbus.cpp.i
.PHONY : video/install-dbus.i

# target to preprocess a source file
video/install-dbus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-dbus.cpp.i
.PHONY : video/install-dbus.cpp.i

video/install-dbus.s: video/install-dbus.cpp.s
.PHONY : video/install-dbus.s

# target to generate assembly for a file
video/install-dbus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-dbus.cpp.s
.PHONY : video/install-dbus.cpp.s

video/install-portproton.o: video/install-portproton.cpp.o
.PHONY : video/install-portproton.o

# target to build an object file
video/install-portproton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-portproton.cpp.o
.PHONY : video/install-portproton.cpp.o

video/install-portproton.i: video/install-portproton.cpp.i
.PHONY : video/install-portproton.i

# target to preprocess a source file
video/install-portproton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-portproton.cpp.i
.PHONY : video/install-portproton.cpp.i

video/install-portproton.s: video/install-portproton.cpp.s
.PHONY : video/install-portproton.s

# target to generate assembly for a file
video/install-portproton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-portproton.cpp.s
.PHONY : video/install-portproton.cpp.s

video/install-video-drivers.o: video/install-video-drivers.cpp.o
.PHONY : video/install-video-drivers.o

# target to build an object file
video/install-video-drivers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-video-drivers.cpp.o
.PHONY : video/install-video-drivers.cpp.o

video/install-video-drivers.i: video/install-video-drivers.cpp.i
.PHONY : video/install-video-drivers.i

# target to preprocess a source file
video/install-video-drivers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-video-drivers.cpp.i
.PHONY : video/install-video-drivers.cpp.i

video/install-video-drivers.s: video/install-video-drivers.cpp.s
.PHONY : video/install-video-drivers.s

# target to generate assembly for a file
video/install-video-drivers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-video-drivers.cpp.s
.PHONY : video/install-video-drivers.cpp.s

video/install-vulkan.o: video/install-vulkan.cpp.o
.PHONY : video/install-vulkan.o

# target to build an object file
video/install-vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-vulkan.cpp.o
.PHONY : video/install-vulkan.cpp.o

video/install-vulkan.i: video/install-vulkan.cpp.i
.PHONY : video/install-vulkan.i

# target to preprocess a source file
video/install-vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-vulkan.cpp.i
.PHONY : video/install-vulkan.cpp.i

video/install-vulkan.s: video/install-vulkan.cpp.s
.PHONY : video/install-vulkan.s

# target to generate assembly for a file
video/install-vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arch-post-installer.dir/build.make CMakeFiles/arch-post-installer.dir/video/install-vulkan.cpp.s
.PHONY : video/install-vulkan.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... arch-post-installer_autogen"
	@echo "... arch-post-installer"
	@echo "... app-centers/install-flatpak-software.o"
	@echo "... app-centers/install-flatpak-software.i"
	@echo "... app-centers/install-flatpak-software.s"
	@echo "... app-centers/install-flatpak.o"
	@echo "... app-centers/install-flatpak.i"
	@echo "... app-centers/install-flatpak.s"
	@echo "... app-centers/install-snapd.o"
	@echo "... app-centers/install-snapd.i"
	@echo "... app-centers/install-snapd.s"
	@echo "... arch-post-installer_autogen/mocs_compilation.o"
	@echo "... arch-post-installer_autogen/mocs_compilation.i"
	@echo "... arch-post-installer_autogen/mocs_compilation.s"
	@echo "... cleaning/clear-font-cache.o"
	@echo "... cleaning/clear-font-cache.i"
	@echo "... cleaning/clear-font-cache.s"
	@echo "... cleaning/install-system-clean.o"
	@echo "... cleaning/install-system-clean.i"
	@echo "... cleaning/install-system-clean.s"
	@echo "... create-sh-file.o"
	@echo "... create-sh-file.i"
	@echo "... create-sh-file.s"
	@echo "... de/install-de-cinnamon.o"
	@echo "... de/install-de-cinnamon.i"
	@echo "... de/install-de-cinnamon.s"
	@echo "... de/install-de-deepin.o"
	@echo "... de/install-de-deepin.i"
	@echo "... de/install-de-deepin.s"
	@echo "... de/install-de-enl.o"
	@echo "... de/install-de-enl.i"
	@echo "... de/install-de-enl.s"
	@echo "... de/install-de-lxde.o"
	@echo "... de/install-de-lxde.i"
	@echo "... de/install-de-lxde.s"
	@echo "... de/install-de-lxqt.o"
	@echo "... de/install-de-lxqt.i"
	@echo "... de/install-de-lxqt.s"
	@echo "... de/install-de-mate.o"
	@echo "... de/install-de-mate.i"
	@echo "... de/install-de-mate.s"
	@echo "... de/install-de-plasma.o"
	@echo "... de/install-de-plasma.i"
	@echo "... de/install-de-plasma.s"
	@echo "... de/install-de-xfce4.o"
	@echo "... de/install-de-xfce4.i"
	@echo "... de/install-de-xfce4.s"
	@echo "... de/install-gnome.o"
	@echo "... de/install-gnome.i"
	@echo "... de/install-gnome.s"
	@echo "... general/install-auto-freq.o"
	@echo "... general/install-auto-freq.i"
	@echo "... general/install-auto-freq.s"
	@echo "... general/install-freq.o"
	@echo "... general/install-freq.i"
	@echo "... general/install-freq.s"
	@echo "... general/install-keys.o"
	@echo "... general/install-keys.i"
	@echo "... general/install-keys.s"
	@echo "... general/install-make-tools.o"
	@echo "... general/install-make-tools.i"
	@echo "... general/install-make-tools.s"
	@echo "... general/install-mirrors.o"
	@echo "... general/install-mirrors.i"
	@echo "... general/install-mirrors.s"
	@echo "... general/install-system-tools.o"
	@echo "... general/install-system-tools.i"
	@echo "... general/install-system-tools.s"
	@echo "... greeter/install-greeter.o"
	@echo "... greeter/install-greeter.i"
	@echo "... greeter/install-greeter.s"
	@echo "... install-networking.o"
	@echo "... install-networking.i"
	@echo "... install-networking.s"
	@echo "... install-proc.o"
	@echo "... install-proc.i"
	@echo "... install-proc.s"
	@echo "... kernels/install-lqx.o"
	@echo "... kernels/install-lqx.i"
	@echo "... kernels/install-lqx.s"
	@echo "... kernels/install-pf-kernel.o"
	@echo "... kernels/install-pf-kernel.i"
	@echo "... kernels/install-pf-kernel.s"
	@echo "... kernels/install-tkg-kernel.o"
	@echo "... kernels/install-tkg-kernel.i"
	@echo "... kernels/install-tkg-kernel.s"
	@echo "... kernels/install-xanmod.o"
	@echo "... kernels/install-xanmod.i"
	@echo "... kernels/install-xanmod.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... misc/install-dev-tools.o"
	@echo "... misc/install-dev-tools.i"
	@echo "... misc/install-dev-tools.s"
	@echo "... misc/install-wine.o"
	@echo "... misc/install-wine.i"
	@echo "... misc/install-wine.s"
	@echo "... one-row-scripts.o"
	@echo "... one-row-scripts.i"
	@echo "... one-row-scripts.s"
	@echo "... optimization/enable-trim.o"
	@echo "... optimization/enable-trim.i"
	@echo "... optimization/enable-trim.s"
	@echo "... optimization/install-ananicy.o"
	@echo "... optimization/install-ananicy.i"
	@echo "... optimization/install-ananicy.s"
	@echo "... optimization/install-haveged.o"
	@echo "... optimization/install-haveged.i"
	@echo "... optimization/install-haveged.s"
	@echo "... optimization/install-nohang.o"
	@echo "... optimization/install-nohang.i"
	@echo "... optimization/install-nohang.s"
	@echo "... optimization/install-rng.o"
	@echo "... optimization/install-rng.i"
	@echo "... optimization/install-rng.s"
	@echo "... optimization/install-zramswap.o"
	@echo "... optimization/install-zramswap.i"
	@echo "... optimization/install-zramswap.s"
	@echo "... privacy/install-internet-tools.o"
	@echo "... privacy/install-internet-tools.i"
	@echo "... privacy/install-internet-tools.s"
	@echo "... privacy/install-messengers.o"
	@echo "... privacy/install-messengers.i"
	@echo "... privacy/install-messengers.s"
	@echo "... privacy/install-security-tools.o"
	@echo "... privacy/install-security-tools.i"
	@echo "... privacy/install-security-tools.s"
	@echo "... sound/install-alsa-sound.o"
	@echo "... sound/install-alsa-sound.i"
	@echo "... sound/install-alsa-sound.s"
	@echo "... sound/install-audio-players.o"
	@echo "... sound/install-audio-players.i"
	@echo "... sound/install-audio-players.s"
	@echo "... sound/install-bluetooth-actions.o"
	@echo "... sound/install-bluetooth-actions.i"
	@echo "... sound/install-bluetooth-actions.s"
	@echo "... sound/install-pipewire-sound.o"
	@echo "... sound/install-pipewire-sound.i"
	@echo "... sound/install-pipewire-sound.s"
	@echo "... sound/install-pulse-audio.o"
	@echo "... sound/install-pulse-audio.i"
	@echo "... sound/install-pulse-audio.s"
	@echo "... tweaks/gnome-tweaks.o"
	@echo "... tweaks/gnome-tweaks.i"
	@echo "... tweaks/gnome-tweaks.s"
	@echo "... tweaks/optimize-cinnamon.o"
	@echo "... tweaks/optimize-cinnamon.i"
	@echo "... tweaks/optimize-cinnamon.s"
	@echo "... tweaks/plasma-tweaks.o"
	@echo "... tweaks/plasma-tweaks.i"
	@echo "... tweaks/plasma-tweaks.s"
	@echo "... tweaks/xfce4-tweaks.o"
	@echo "... tweaks/xfce4-tweaks.i"
	@echo "... tweaks/xfce4-tweaks.s"
	@echo "... video/install-dbus.o"
	@echo "... video/install-dbus.i"
	@echo "... video/install-dbus.s"
	@echo "... video/install-portproton.o"
	@echo "... video/install-portproton.i"
	@echo "... video/install-portproton.s"
	@echo "... video/install-video-drivers.o"
	@echo "... video/install-video-drivers.i"
	@echo "... video/install-video-drivers.s"
	@echo "... video/install-vulkan.o"
	@echo "... video/install-vulkan.i"
	@echo "... video/install-vulkan.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

